version: "3.5"
services: 
    app:
      build: ./app
      container_name: geekflix_node
      volumes: 
        - ./app:/app
        - /app/node_modules
      ports: 
        - 3001:3000
    sass:
      image: larryprice/sass
      volumes:
        - ./app/src/css:/src     